[project]
name = "quantum-papers-implementations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nbformat>=5.10.4",
    "pennylane-qiskit>=0.43.0",
    "pylatexenc>=2.10",
    "qiskit>=2.1.2",
]
